manala:
    description: Symfony application using a Docker-hybrid stack
    template: .manala.yaml.tmpl
    sync:
        - .manala/
        - docker-compose.yaml.tmpl
        - docker-compose.override.yaml.tmpl
        - php.ini.tmpl

system:
    # @option {"label": "App name (in kebab-case)"}
    # @schema {"type": "string"}
    app_name: ~
    # @schema {"type": ["string"], "pattern": "^[a-zA-Z]+/[a-zA-Z]+$"}
    timezone: Etc/UTC
    php:
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "config": {"type": ["object", "string", "array"]}
        #         }
        #     }
        # }
        configs: []
    mysql:
        # @option {"label": "MySQL version"}
        # @schema {"enum": [null, "8.0", 5.7]}
        version: ~
        # @schema {"type": ["string", "null"]}
        init: ~
        # @schema {"type": ["string", "null"]}
        additional_config:
    mariadb:
        # @option {"label": "MariaDB version"}
        # @schema {"enum": [null, 10.11, 10.6, 10.5, 10.4, 10.3, 10.2, 10.1]}
        version: ~
        # @schema {"type": ["string", "null"]}
        init: ~
        # @schema {"type": ["string", "null"]}
        additional_config:
    redis:
        # @option {"label": "Redis version"}
        # @schema {"enum": [null, "*"]}
        version: ~
    mailcatcher:
        # @option {"label": "Mailcatcher version"}
        # @schema {"enum": [null, "*"]}
        version: ~
