manala:
    description: Wamiz - Symfony application using a Docker-hybrid stack
    template: .manala.yaml.tmpl
    sync:
        - .manala/
        - docker-compose.yaml.tmpl
        - php.ini.tmpl

system:
    # @option {"label": "App name (in kebab-case)"}
    # @schema {"type": "string"}
    app_name: ~
    # @schema {"type": ["string"], "pattern": "^[a-zA-Z]+/[a-zA-Z]+$"}
    timezone: Etc/UTC
    php:
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "config": {"type": ["object", "string", "array"]}
        #         }
        #     }
        # }
        configs: []
    mysql:
        # @option {"label": "MySQL version"}
        # @schema {"enum": [null, 5.7, 8, "8.0"]}
        version: ~
        # @schema {"type": ["string", "null"]}
        init: ~
    redis:
        # @option {"label": "Redis version"}
        # @schema {"enum": [null, "*"]}
        version: ~
    mailcatcher:
        # @option {"label": "Mailcatcher version"}
        # @schema {"enum": [null, "*"]}
        version: ~
